---
- Name: installing windows softwares
  Hosts: all
  Gather_facts: false
  Tasks:
    - name: Deploy IIS
      win_feature:
        name: web-server
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
    - name: Install chrome
      win_chocolatey:
        Name: “googlechrome”
        State: latest
    - name: Download new relic
      win_get_url:
        url: https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.msi
        dest: C:\newrelic-infra.msi
    - name: Install new relic
      win_package:
        path: C:\newrelic-infra.msi
        state: present
    - name: install Octopus Tentacle using chocolatey
      win_chocolatey:
        name: octopusdeploy.tentacle
        pinned: yes
        state: present
    - name: Restart Octopus service
      win_service:
        name: OctopusDeploy Tentacle
        start_mode: delayed
        state: restarted
    - name: Install Splunk Forwarder
      win_chocolatey:
        name: splunk-universalforwarder
        state: present
    - name: Install cntlm auth proxy
      win_chocolatey:
        name: cntlm
        state: present
    - name: Start the cntlm service
      win_service:
        name: cntlm
        state: restarted
    - name: Install chub scrapper
      win_chocolatey:
        name: scrapy
        state: present
